import { Phone } from "@/types/productsTypes"

export const arraysPhones: Phone[] = [
  // 📱 TELÉFONOS
  {
    id: 1,
    type: 'phone',
    brand: 'Apple',
    model: 'iPhone 11',
    price: 18500,
    storage: '128GB',
    condition: 'Usado',
    image: '/phones/iphone-11.jpg',
  },
  {
    id: 2,
    type: 'phone',
    brand: 'Apple',
    model: 'iPhone 12',
    price: 26000,
    storage: '128GB',
    condition: 'Reacondicionado',
    image: '/phones/iphone-12.jpg',
  },
  {
    id: 3,
    type: 'phone',
    brand: 'Apple',
    model: 'iPhone 13',
    price: 35000,
    storage: '128GB',
    condition: 'Nuevo',
    image: '/phones/iphone-13.jpg',
  },
  {
    id: 4,
    type: 'phone',
    brand: 'Samsung',
    model: 'Galaxy S21',
    price: 23000,
    storage: '128GB',
    condition: 'Usado',
    image: '/phones/galaxy-s21.jpg',
  },
  {
    id: 5,
    type: 'phone',
    brand: 'Samsung',
    model: 'Galaxy S22',
    price: 31000,
    storage: '256GB',
    condition: 'Nuevo',
    image: '/phones/galaxy-s22.jpg',
  },
  {
    id: 6,
    type: 'phone',
    brand: 'Xiaomi',
    model: 'Redmi Note 12',
    price: 11000,
    storage: '128GB',
    condition: 'Nuevo',
    image: '/phones/redmi-note-12.jpg',
  },

  // 🎧 ACCESORIOS
  {
    id: 101,
    type: 'accessory',
    brand: 'Apple',
    model: 'AirPods 2',
    price: 8500,
    image: '/accessories/airpods-2.jpg',
  },
  {
    id: 102,
    type: 'accessory',
    brand: 'Samsung',
    model: 'Galaxy Buds Live',
    price: 6200,
    image: '/accessories/galaxy-buds.jpg',
  },
  {
    id: 103,
    type: 'accessory',
    brand: 'Xiaomi',
    model: 'Power Bank 20000mAh',
    price: 3200,
    image: '/accessories/powerbank-xiaomi.jpg',
  },
  {
    id: 104,
    type: 'accessory',
    brand: 'Baseus',
    model: 'Cargador rápido USB-C 65W',
    price: 2800,
    image: '/accessories/baseus-charger.jpg',
  },
  {
    id: 105,
    type: 'accessory',
    brand: 'Anker',
    model: 'Cable USB-C a Lightning',
    price: 1500,
    image: '/accessories/anker-cable.jpg',
  },
]
